Modules/CRM/Http/routes.php
<?php

Route::group(['middleware' => 'web', 'prefix' => 'crm', 'namespace' => 'Modules\CRM\Http\Controllers'], function()
{
    Route::get('/', 'CRMController@index');

    /**
     * Main
     */
        Route::get('/', 'CRMController@index');
        Route::get('index', 'CRMController@index')->name('dashboard');
        

	
    /**
     * Clients
     */
    Route::group(['prefix' => 'clients'], function () {
        Route::get('/', 'ClientsController@index')->name('clients.index');
        Route::get('/data', 'ClientsController@anyData')->name('clients.data');
        Route::get('/create', 'ClientsController@create')->name('clients.create');
        Route::post('/create/cvrapi', 'ClientsController@cvrapiStart');
        Route::post('/upload/{id}', 'DocumentsController@upload');
        Route::patch('/updateassign/{id}', 'ClientsController@updateAssign');
        Route::get('/{client}', 'ClientsController@show');
    });
        Route::resource('clients', 'ClientsController');
	    Route::resource('documents', 'DocumentsController');
	
      
    /**
     * Tasks
     */
    Route::group(['prefix' => 'tasks'], function () {
        Route::get('/data', 'TasksController@anyData')->name('tasks.data');
        Route::get('/add', 'TasksController@create');
        Route::get('/{id}', 'TasksController@show')->name
        ('tasks.show');
        Route::patch('/updatestatus/{id}', 'TasksController@updateStatus');
        Route::patch('/updateassign/{id}', 'TasksController@updateAssign');
        Route::post('/updatetime/{id}', 'TasksController@updateTime');
    });
        Route::resource('tasks', 'TasksController');

    /**
     * Leads
     */
    Route::group(['prefix' => 'leads'], function () {
        Route::get('/data', 'LeadsController@anyData')->name('leads.data');
        Route::get('/add', 'LeadsController@create');
        Route::get('/{id}', 'LeadsController@show')->name('leads.show');
        Route::patch('/updateassign/{id}', 'LeadsController@updateAssign');
        Route::patch('/updatestatus/{id}', 'LeadsController@updateStatus');
        Route::patch('/updatefollowup/{id}', 'LeadsController@updateFollowup')->name('leads.followup');
    });
        Route::resource('leads', 'LeadsController');
        Route::post('/comments/{type}/{id}', 'CommentController@store');
     

    /**
     * Integrations
     */
    Route::group(['prefix' => 'integrations'], function () {
        Route::get('Integration/slack', 'IntegrationsController@slack');
    });
        Route::resource('integrations', 'IntegrationsController');

    

    /**
     * Invoices
     */
    Route::group(['prefix' => 'invoices'], function () {
        Route::patch('/updatepayment/{id}', 'InvoicesController@updatePayment')->name('invoice.payment.date');
        Route::patch('/reopenpayment/{id}', 'InvoicesController@reopenPayment')->name('invoice.payment.reopen');
        Route::post('/sentinvoice/{id}', 'InvoicesController@updateSentStatus')->name('invoice.sent');
        Route::post('/newitem/{id}', 'InvoicesController@newItem')->name('invoice.new.item');
    });
        Route::resource('invoices', 'InvoicesController');
});

Modules/CRM/Entities/Lead.php
<?php

namespace Modules\CRM\Entities;

use Illuminate\Database\Eloquent\Model;
use Carbon\Carbon;
use Zana\User;

class Lead extends Model
{
    protected $fillable = [
        'title',
        'description',
        'status',
        'user_assigned_id',
        'user_created_id',
        'client_id',
        'contact_date',

    ];
    protected $dates = ['contact_date'];

    protected $hidden = ['remember_token'];

    public function user()
    {
        return $this->belongsTo(User::class, 'user_assigned_id');
    }

    public function creator()
    {
        return $this->belongsTo(User::class, 'user_created_id');
    }

    public function client()
    {
        return $this->belongsTo(Client::class, 'client_id');
    }
    
    public function comments()
    {
        return $this->morphMany(Comment::class, 'source');
    }

    public function activity()
    {
        return $this->morphMany(Activity::class, 'source');
    }

    public function getDaysUntilContactAttribute()
    {
        return Carbon::now()->startOfDay()->diffInDays($this->contact_date, false);
    }

    /**
     * Add a reply to the thread.
     *
     * @param  array $reply
     * @return Model
     */
    public function addComment($reply)
    {
        $reply = $this->comments()->create($reply);
        return $reply;
    }
}

Modules/CRM/Http/Controllers/LeadsController.php
<?php

namespace Modules\CRM\Http\Controllers;

use DB;
use Auth;
use Carbon\Carbon;
use Session;
use Datatables;
use Modules\CRM\Entities\Lead;
use Illuminate\Http\Request;
use Modules\CRM\Requests;
use Modules\CRM\Http\Requests\StoreLeadRequest;
use Modules\CRM\Repositories\Lead\LeadRepositoryContract;
use Modules\CRM\Repositories\User\UserRepositoryContract;
use Modules\CRM\Http\Requests\UpdateLeadFollowUpRequest;
use Modules\CRM\Repositories\Client\ClientRepositoryContract;
use Modules\CRM\Repositories\Setting\SettingRepositoryContract;
use Illuminate\Routing\Controller;
use Zana\User;

class LeadsController extends Controller
{
    protected $leads;
    protected $clients;
    protected $settings;
    protected $users;

    public function __construct(
        LeadRepositoryContract $leads,
        UserRepositoryContract $users,
        ClientRepositoryContract $clients,
        SettingRepositoryContract $settings
    )
    {
        $this->users = $users;
        $this->settings = $settings;
        $this->clients = $clients;
        $this->leads = $leads;
        $this->middleware('auth');
        $this->middleware('lead.create', ['only' => ['create']]);
        $this->middleware('lead.assigned', ['only' => ['updateAssign']]);
        $this->middleware('lead.update.status', ['only' => ['updateStatus']]);
    }
    /**
     * Display a listing of the resource.
     * @return Response
     */
    public function index()
    {
        $leads = Lead::all();
        return view('crm::leads.index', compact('leads'));
    }

    /**
     * Data for Data tables
     * @return mixed
     */
    public function anyData()
    {
        $leads = Lead::select(
            ['id', 'title', 'user_created_id', 'client_id', 'user_assigned_id', 'contact_date']
        )->where('status', 1)->get();
        return Datatables::of($leads)
            ->addColumn('titlelink', function ($leads) {
                return '<a href="crm/leads/' . $leads->id . '" ">' . $leads->title . '</a>';
            })
            ->editColumn('user_created_id', function ($leads) {
                return $leads->creator->name;
            })
            ->editColumn('contact_date', function ($leads) {
                return $leads->contact_date ? with(new Carbon($leads->contact_date))
                    ->format('d/m/Y') : '';
            })
            ->editColumn('user_assigned_id', function ($leads) {
                return $leads->user->name;
            })->make(true);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $users = User::pluck('name','id');
        return view('crm::leads.create', compact('users'))            
            ->withClients($this->clients->listAllClients());
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param StoreLeadRequest|Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreLeadRequest $request)
    {
        $getInsertedId = $this->leads->create($request);
        Session()->flash('flash_message', 'Lead is created');
        return redirect()->route('leads.show', $getInsertedId);
    }

    public function updateAssign($id, Request $request)
    {
        $this->leads->updateAssign($id, $request);
        Session()->flash('flash_message', 'New user is assigned');
        return redirect()->back();
    }

    /**
     * Update the follow up date (Deadline)
     * @param UpdateLeadFollowUpRequest $request
     * @param $id
     * @return mixed
     */
    public function updateFollowup(UpdateLeadFollowUpRequest $request, $id)
    {
        $this->leads->updateFollowup($id, $request);
        Session()->flash('flash_message', 'New follow up date is set');
        return redirect()->back();
    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $users = User::pluck('name','id');
        return view('crm::leads.show', compact('users'))
            ->withLead($this->leads->find($id))
            ->withCompanyname($this->settings->getCompanyName());
    }

    /**
     * Complete lead
     * @param $id
     * @param Request $request
     * @return mixed
     */
    public function updateStatus($id, Request $request)
    {
        $this->leads->updateStatus($id, $request);
        Session()->flash('flash_message', 'Lead is completed');
        return redirect()->back();
    }
}

Modules/CRM/Resources/views/leads/create.blade.php
@extends('crm::layouts.master')

@section('heading')

@endsection
@section('bg-color')
@endsection

@section('content')

    <!-- START PANEL -->
<div class="container-fluid container-fixed-lg">
<div class="row">
  <div class="col-lg-7 col-md-6 ">
    <!-- START PANEL -->
    <div class="panel panel-transparent">
      <div class="panel-body">
      	{!! Form::open([
            'route' => 'leads.store',
            'class' => 'ui-form',
            'id' => 'form-personal',
            'autocomplete' => 'off',
            'role' => 'form'
            ]) !!}
          @include('crm::leads/form', ['submitButtonText' => __('Create New Lead')])
        {!! Form::close() !!}
      </div>
    </div>
    <!-- END PANEL -->
  </div>
  <div class="col-lg-5 col-md-6">
    <!-- START PANEL -->
    <div class="panel panel-White">
      <div class="panel-heading">
        <div class="panel-title">Create a New Lead
        </div>
      </div>
      <div class="panel-body">
        <h3>Mandatory Field are marked</h3>
        <p>Forms are one of the most important components
          <br> when it comes to a dashboard. Recognizing that fact, users are
          <br>able work in a maximum content width.</p>
        <br>
        <p class="small hint-text m-t-5">A lead usually is the contact information and in some cases, demographic information of a customer who is interested in a specific product or service. There are two types of leads in the lead generation market: sales leads and marketing leads.</p>
        <p class="small hint-text m-t-5"><strong>Sales leads</strong> are generated on the basis of demographic criteria such as FICO score, income, age, household income, psychographic, etc. These leads are resold to multiple advertisers. Sales leads are typically followed up through phone calls by the sales force. Sales leads are commonly found in the mortgage, insurance and finance industries.</p>
        <p class="small hint-text m-t-5"></p>
        <button class="btn btn-primary btn-cons">More</button>
      </div>
    </div>
    <!-- END PANEL -->
  </div>
</div>
</div>
@endsection

@push('styles')
<link href="{{ asset('assets/plugins/bootstrap3-wysihtml5/bootstrap3-wysihtml5.min.css') }}" rel="stylesheet" type="text/css" />
<link href="{{ asset('assets/plugins/bootstrap-tag/bootstrap-tagsinput.css') }}" rel="stylesheet" type="text/css" />
<link href="{{ asset('assets/plugins/dropzone/css/dropzone.css') }}" rel="stylesheet" type="text/css" />
<link href="{{ asset('assets/plugins/bootstrap-datepicker/css/datepicker3.css') }}" rel="stylesheet" type="text/css" media="screen">
<link href="{{ asset('assets/plugins/summernote/css/summernote.css') }}" rel="stylesheet" type="text/css" media="screen">
<link href="{{ asset('assets/plugins/bootstrap-daterangepicker/daterangepicker-bs3.css') }}" rel="stylesheet" type="text/css" media="screen">
<link href="{{ asset('assets/plugins/bootstrap-timepicker/bootstrap-timepicker.min.css') }}" rel="stylesheet" type="text/css" media="screen">
@endpush
@push('scripts')
<script type="text/javascript" src="{{ asset('assets/plugins/jquery-inputmask/jquery.inputmask.min.js') }}"></script>
<script src="{{ asset('assets/plugins/bootstrap-form-wizard/js/jquery.bootstrap.wizard.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('assets/plugins/jquery-validation/js/jquery.validate.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('assets/plugins/bootstrap-datepicker/js/bootstrap-datepicker.js') }}" type="text/javascript"></script>
<script src="{{ asset('assets/plugins/bootstrap-daterangepicker/daterangepicker.js') }}"></script>
<script src="{{ asset('assets/plugins/bootstrap-timepicker/bootstrap-timepicker.min.js') }}"></script>
<script src="{{ asset('assets/js/form_elements.js') }}" type="text/javascript"></script>
@endpush

Modules/CRM/Resources/views/leads/form.blade.php
<div class="row clearfix">
    <div class="col-sm-12">
        <div class="form-group form-group-default required">
            {!! Form::label('title', __('Title'), ['class' => 'control-label']) !!}
            {!! Form::text('title', null, ['class' => 'form-control']) !!}
        </div>
    </div>
</div>
<div class="row">
    <div class="col-sm-12">
        <div class="form-group form-group-default">
            {!! Form::label('description', __('Description'), ['class' => 'control-label']) !!}
            {!! Form::textarea('description', null, ['class' => 'form-control']) !!}
        </div>
    </div>
</div>
<div class="row">
    <div class="col-sm-4">
        <div class="form-group col-lg-3 removeleft">
            {!! Form::label('status', __('Status'), ['class' => 'control-label']) !!}
            {!! Form::select('status', array(
            '1' => 'Contact Client', '2' => 'Completed'), null, ['class' => 'cs-select cs-skin-slide', 'data-init-plugin' => 'cs-select'] )
         !!}
        </div>
    </div>
    <div class="col-sm-4">
        <div class="form-group form-group-default input-group col-sm-10">
            {!! Form::label('contact_date', __('Deadline'), ['class' => 'control-label']) !!}
            {!! Form::date('contact_date', Carbon\Carbon::now()->addDays(7), ['class' => 'form-control']) !!}
        </div>
    </div>
    <div class="col-sm-4">
        <div class="form-group form-group-default input-group col-sm-10">
            {!! Form::label('contact_time', __('Time'), ['class' => 'control-label']) !!}
            {!! Form::time('contact_time', '11:00', ['class' => 'form-control', 'id' => 'timepicker']) !!}
            <span class="input-group-addon"><i class="far fa-clock"></i></span>
        </div>
    </div>
</div>
<div class="row">
<div class="col-sm-6">
    <div class="form-group form-group-default form-group-default-select2">
        {!! Form::label('user_assigned_id', __('Assign user'), ['class' => 'control-label']) !!}
        {!! Form::select('user_assigned_id', $users, null, ['class' => 'full-width', 'data-init-plugin' => 'select2']) !!}
    </div>
</div>
<div class="col-sm-6">
    <div class="form-group form-group-default form-group-default-select2">
        @if(Request::get('client') != "")
            {!! Form::hidden('client_id', Request::get('client')) !!}
        @else
            {!! Form::label('client_id', __('Assign client'), ['class' => 'control-label']) !!}
            {!! Form::select('client_id', $clients, null, ['class' => 'full-width', 'data-init-plugin' => 'select2']) !!}
        @endif
    </div>
</div>
</div>
<div class="clearfix"></div>
    {!! Form::submit($submitButtonText, ['class' => 'btn btn-primary']) !!}
	   
	

Modules/CRM/Resources/views/leads/index.blade.php
@extends('crm::layouts.master')

@section('heading')
    <h1>{{__('All leads')}}</h1>
@stop

@section('content')
    <table class="table table-hover" id="leads-table">
        <thead>
        <tr>

            <th>{{ __('Lead Name') }}</th>
            <th>{{ __('Company')}}</th>
            <th>{{ __('Created by') }}</th>
            <th>{{ __('Contact Data') }}</th>
            <th>{{ __('Assigned') }}</th>

        </tr>
        </thead>
        <tbody>
            
                @foreach($leads as $lead)
                <tr>
                <td><a href="leads/{{$lead->id}}">{{$lead->title}}</a></td>
                <td><a href="/crm/clients/{{$lead->client_id}}"> {{$lead->client->name}} </a></td>
                <td>{{$lead->creator->name}}</td>
                <td>{{$lead->contact_date->toFormattedDateString()}}</td>
                <td>{{$lead->user->name}}</td>
                </tr>
                @endforeach
            
        </tbody>
    </table>
@stop

Modules/CRM/Resources/views/leads/show.blade.php
@extends('crm::layouts.master')

@section('heading')

@stop

@section('content')
@push('scripts')
    <script>
        $(document).ready(function () {
            $('[data-toggle="tooltip"]').tooltip();
        });
    </script>
@endpush
<div class="container-fluid container-fixed-lg">
    
    <div class="row">
        <div class="col-md-6">
            @include('crm::partials.comments', ['subject' => $lead])
        </div>
        <div class="col-md-6">
            <div class="sidebarheader">
                <p> {{ __('Lead information') }}</p>
            </div>
            <div class="sidebarbox">
                <p>{{ __('Assigned to') }}:
                    <a href="{{route('leads.show', $lead->user->id)}}">
                        {{$lead->user->name}}</a></p>
                <p>{{ __('Created at') }}: {{ date('d F, Y, H:i', strtotime($lead->created_at))}} </p>
                @if($lead->days_until_contact < 2)
                    <p>{{ __('Follow up') }}: <span style="color:red;">{{$lead->contact_date->toDayDateTimeString()}}

                            @if($lead->status == 1) ({!! $lead->days_until_contact !!}) @endif</span> <i
                                class="glyphicon glyphicon-calendar" data-toggle="modal"
                                data-target="#ModalFollowUp"></i></p> <!--Remove days left if lead is completed-->

                @else
                    <p>{{ __('Follow up') }}: <span style="color:green;">{{$lead->contact_date->toDayDateTimeString()}}

                            @if($lead->status == 1) ({!! $lead->days_until_contact !!})<i
                                    class="glyphicon glyphicon-calendar" data-toggle="modal"
                                    data-target="#ModalFollowUp"></i>@endif</span></p>
                    <!--Remove days left if lead is completed-->
                @endif
                @if($lead->status == 1)
                    {{ __('Status') }}: {{ __('Contact') }}
                @elseif($lead->status == 2)
                    {{ __('Status') }}: {{ __('Completed') }}
                @elseif($lead->status == 3)
                    {{ __('Status') }}: {{ __('Not interested') }}
                @endif

            </div>
            @if($lead->status == 1)
                {!! Form::model($lead, [
               'method' => 'PATCH',
                'url' => ['crm/leads/updateassign', $lead->id],
                ]) !!}
                {!! Form::select('user_assigned_id', $users, null, ['class' => 'form-control ui search selection top right pointing search-select', 'id' => 'search-select']) !!}
                {!! Form::submit(__('Assign new user'), ['class' => 'btn btn-primary form-control closebtn']) !!}
                {!! Form::close() !!}
                {!! Form::model($lead, [
               'method' => 'PATCH',
               'url' => ['crm/leads/updatestatus', $lead->id],
               ]) !!}

                {!! Form::submit(__('Complete Lead'), ['class' => 'btn btn-success form-control closebtn movedown']) !!}
                {!! Form::close() !!}
            @endif

            <div class="activity-feed movedown">
                @foreach($lead->activity as $activity)

                    <div class="feed-item">
                        <div class="activity-date">{{date('d, F Y H:i', strTotime($activity->created_at))}}</div>
                        <div class="activity-text">{{$activity->text}}</div>

                    </div>
                @endforeach
            </div>
        </div>

    </div>


    <div class="modal fade" id="ModalFollowUp" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                                aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="myModalLabel">{{ __('Change deadline') }}</h4>
                </div>

                <div class="modal-body">

                    {!! Form::model($lead, [
                      'method' => 'PATCH',
                      'route' => ['leads.followup', $lead->id],
                      ]) !!}
                    {!! Form::label('contact_date', __('Next follow up'), ['class' => 'control-label']) !!}
                    {!! Form::date('contact_date', \Carbon\Carbon::now()->addDays(7), ['class' => 'form-control']) !!}
                    {!! Form::time('contact_time', '11:00', ['class' => 'form-control']) !!}


                    <div class="modal-footer">
                        <button type="button" class="btn btn-default col-lg-6"
                                data-dismiss="modal">{{ __('Close') }}</button>
                        <div class="col-lg-6">
                            {!! Form::submit( __('Update follow up'), ['class' => 'btn btn-success form-control closebtn']) !!}
                        </div>
                        {!! Form::close() !!}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

@section('jumbotron')
<div class="jumbotron page-cover" data-pages="parallax">
    <div class="container-fluid container-fixed-lg">
      <div class="inner" style="transform: translateY(0px); opacity: 1;">
        <!-- START BREADCRUMB -->
        @yield('wizard.breadcrumb')
        <!-- END BREADCRUMB -->
        <div class="container-md-height m-b-20">
          <div class="row row-md-height">
            <!-- Client Header -->
            @include('crm::partials.clientheader')
            <!-- End Client Header -->
            <!-- User Header -->
            @include('crm::partials.userheader')
            <!-- End User Header -->
          </div>
        </div>
      </div>
    </div>
  </div>
@endsection

Modules/CRM/Resources/views/leads/sidebar.blade.php
<div class="bg-white full-height">
    <div class="panel panel-transparent">
        <div class="panel-heading">
            <div class="panel-title">{{ __('Lead information') }}</div>
        </div>
        <div class="panel-body">
            <div class="row">
                <h5 class="font-arial no-margin">{{ __('Assigned to') }}</h5>
                <p class="hint-text">
                    <a href="{{route('leads.show', $lead->user->id)}}">
                        {{$lead->user->name}}</a>
                    </p>
            </div>
            <div class="row">
                <h5 class="font-arial no-margin">{{ __('Created at') }}</h5>
                <p class="hint-text">{{ date('d F, Y, H:i', strtotime($lead->created_at))}}</p>
            </div>
            @if($lead->days_until_contact < 2)
            <div class="row">
                <h5 class="font-arial no-margin">{{ __('Follow up') }}</h5>
                <p class="hint-text">
                    <span style="color:red;">{{date('d, F Y, H:i', strTotime($lead->contact_date))}}

                            @if($lead->status == 1) ({!! $lead->days_until_contact !!}) @endif</span> <i
                                class="glyphicon glyphicon-calendar" data-toggle="modal"
                                data-target="#ModalFollowUp"></i>
                </p>
                <!--Remove days left if lead is completed-->
            </div>
             @else
            <div class="row">
                <h5 class="font-arial no-margin">{{ __('Follow up') }}</h5>
                <p class="hint-text">
                    <span style="color:green;">{{date('d, F Y, H:i', strTotime($lead->contact_date))}}

                            @if($lead->status == 1) ({!! $lead->days_until_contact !!})<i
                                    class="glyphicon glyphicon-calendar" data-toggle="modal"
                                    data-target="#ModalFollowUp"></i>@endif</span>
                </p>
                <!--Remove days left if lead is completed-->
            </div>
            @endif            
            <div class="row">
                <h5 class="font-arial no-margin">{{ __('Status') }}</h5>
                @if($lead->status == 1)
                <p class="hint-text">{{ __('Contact') }}</p>
                @elseif($lead->status == 2)
                <p class="hint-text">{{ __('Completed') }}</p>
                @elseif($lead->status == 3)
                <p class="hint-text">{{ __('Not interested') }}</p>
                @endif
            </div>

        </div>
    </div>
            
            @if($lead->status == 1)
                {!! Form::model($lead, [
               'method' => 'PATCH',
                'url' => ['leads/updateassign', $lead->id],
                ]) !!}
                {!! Form::select('user_assigned_id', $users, null, ['class' => 'form-control ui search selection top right pointing search-select', 'id' => 'search-select']) !!}
                {!! Form::submit(__('Assign new user'), ['class' => 'btn btn-primary form-control closebtn']) !!}
                {!! Form::close() !!}
                {!! Form::model($lead, [
               'method' => 'PATCH',
               'url' => ['leads/updatestatus', $lead->id],
               ]) !!}

                {!! Form::submit(__('Complete Lead'), ['class' => 'btn btn-success form-control closebtn movedown']) !!}
                {!! Form::close() !!}
            @endif

            <div class="activity-feed movedown">
                @foreach($lead->activity as $activity)

                    <div class="feed-item">
                        <div class="activity-date">{{date('d, F Y H:i', strTotime($activity->created_at))}}</div>
                        <div class="activity-text">{{$activity->text}}</div>

                    </div>
                @endforeach
            </div>
        </div>